# Generated by Django 5.0.6 on 2024-09-14 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0003_notification_video_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useradview',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ads_app.video'),
        ),
        migrations.DeleteModel(
            name='Ad',
        ),
    ]
