# Generated by Django 5.0.6 on 2024-09-14 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0004_alter_useradview_ad_delete_ad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='Ad',
        ),
    ]
