# Generated by Django 5.0.6 on 2024-09-15 16:36

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0007_alter_withdrawal_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('checking', 'Checking'), ('active', 'Active')], default='pending', max_length=10),
        ),
    ]
