# Generated by Django 5.0.6 on 2024-09-15 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads_app', '0008_alter_user_managers_user_status'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
